### ISSUE TITLE
Update plan at start of Fall 2018

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1220]
* [x] Persistant Python: #1176 - needs a feature flag and timeout testcase.
* [ ] Config/local grading/dev: #1163 - need to merge corresponding PG PR first, will need new config files on deploy. Need to add new env var to select PROD/STAGING/etc.
* [x] Cache question renders: #1165 - needs a feature flag. Will need a redis in production (shared with pl-dev).
* [ ] HTML validator: #1170 - put it behind the new HTML renderer feature flag. Merge immediately.
* [x] New login screen: #1199 - good to go, test on dev.
* [x] LTI support: #1210 - needs some work still. Matt needs to work with Dave on this.
* [ ] Get courses to turn on feature flag for new HTML renderer. Talk to courses with heavy v3 usage. Need docs for the migration tool.

**Comment by mwest1066** [comment]
We've got PRs for all of these in the queue, so I'm closing out this tracking issue.
