### ISSUE TITLE
Issue Tracker Todos

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1483]
PL Core:

- [ ] Read-only mode warning #1428
- [ ] Magic links to course questions: #1076 (shows dev environment)
- [ ] Improved per question timing accuracy: #1055
- [ ] Student question view: #1065
- [ ] Display Questions on Instructor's page: #1114 

Gradebook:

- [ ] API for Mass Adding/Removal #1481
- [ ] Add a pre-configured CSV for uploading grades: #1384

Elements:

- [ ] PL T/F Element: #1482
- [ ] Matrix support R: #1460 
- [ ] Parson Problems: #1253 
- [ ] PL Templating System: #1121 

Docs:

- [x] FAQ Entries: #1374
- [ ] User Guide Revamp: #1480 
- [ ] Instructor videos: #1384

**Comment by coatless** [comment]
Closing as I can now self-assign issues.
