### ISSUE TITLE
Notes about workspace hosts

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2935]
* [x] How do hosts in state `terminating` eventually get to state `terminated`? If I'm understanding correctly, this will be done by `sql.set_terminated_hosts_if_not_launching` in `cron/workspacesTransition.js`. But this uses `select_nonterminated_or_nonterminating_workspace_hosts` to select the hosts to be terminated, so I don't see how we are ever going to select a `terminating` host to be able to change its state to `terminated`?

* [x] @tdy I think this LEFT JOIN on `workspaces` is not needed: https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_find_terminable.sql#L18

* [x] @tdy I think this `WHERE` clause: https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_find_terminable.sql#L32
Can be more succinctly written as:
```
    UPDATE workspace_hosts AS wh
    SET state = 'terminating',
        state_changed_at = NOW()
    FROM terminable_hosts AS th
    WHERE wh.id = th.id;
```

* [x] @tdy Same `WHERE` change can be applied here: https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_recapture_draining.sql#L22
and here:
https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_drain_extra.sql#L18

* [x] @tdy I think it would be more accurate to shift the `recaptured_hosts` count to be the output of the UPDATE (not the SELECT) because it's not guaranteed that we actually make the same number of UPDATEs (for example, someone else might terminate one of the `found_draining_hosts` before we convert it back to `ready`): https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_recapture_draining.sql#L16
To return a count from an UPDATE we need to put the UPDATE into a CTE (WITH clause). Given this, it might be simpler to also make `found_draining_hosts` another CTE before the UPDATE, instead of using temporary tables.

* [x] @tdy The OUT parameter here should be `terminable_hosts` or `terminating_hosts`, not `terminated_hosts`? https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_hosts_find_terminable.sql#L5

* [x] @tdy I think this file should be called `workspaceHostTransitions.js` or something similar to indicate that it's for workspace _hosts_: https://github.com/PrairieLearn/PrairieLearn/blob/master/cron/workspacesTransition.js

* [x] For safety, I think `db_hosts_running_or_terminating` should be just `db_hosts_running`. That is, any hosts in state `terminating` that are still in the DB should be sent another termination signal. This avoids the case where we have a host that was marked as `terminating` in the DB, but the actual termination signal was never sent, in which case it's a zombie.
https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/cron/workspacesTransition.js#L62

* [x] @nicknytko  It would be good to maintain a hard cap on the number of workspaces running on each host. That is, when we are placing a new workspace:
    * [x] Only select hosts that are `ready` and have fewer than the maximum workspaces on them already.
    * [x] When a host receives an `init` command, it should reject it if it's already at maximum capacity.
    * [x] When a PL server is trying to select a host, if it can't find any, or if the one it tries gives an error, it should: (1) send message "waiting for compute nodes to become available", (2) wait for a random number of seconds, (3) try again.
    * [x] When we compute `workspace_jobs_capacity_desired`, include both `running` and `launching` workspaces so that we will launch more hosts to meet the demand of launching workspaces: https://github.com/PrairieLearn/PrairieLearn/blob/fed9309f4c17bd527ae0578d5919c26ac7478c08/sprocs/workspace_loads_current.sql#L92

* [ ] **(now tracked in #3179)** Use the `Name` tag to group workspace hosts and filter the instances. (so `"Name": "workspace-prod"` or something like that).

* [ ] **(now tracked in #3288)** Paginate the `describeInstances()` call with `NextToken` so we can have more than 500 hosts: https://github.com/PrairieLearn/PrairieLearn/blob/fa82efd6d180f01a1c09e01c2f44d23c407a44bd/cron/workspacesTransition.js#L29

* [x] @tdy Add `workspace_hosts.unhealthy_reason` column and set it. Make sure we only transition to `unhealthy` if we aren't already unhealthy, so the `unhealthy_reason` will be the very first time we detect unhealthy.

* [x] @tdy Don't automatically go to unhealthy if we fail to launch a workspace. This could occur due to user error such as an invalid image name. Instead use a docker daemon health check like PrairieGrader.

* [x] @tdy Implement `_getGradedFilesFromS3()`.

* [x] @tdy Make it so that you don't have to have a `workspace/` directory inside the question. If it's not there, we should just make an empty zip file.

* [x] @tdy Check that Save&Grade does the right thing if `gradedFiles` is either (1) unspecified, or (2) an empty array.

* [x] **(seems to have been fixed already)** ~~`cron/workspacesLoad.js` uses "Running" in some places where it should be "Ready"~~

* [x] Bug where some 357 students get the s3NotImplemented error. @nicknytko will add debug traces.

* [x] @tdy Add more `logger.info()` calls when we launch a workspace, kill a container, etc. Previously: ~~Add file logging to `/var/log/prairielearn.log` on workspace hosts and add it to the files that amazon-cloudwatch-agent sends to cloudwatch.~~ 

* [ ] **(now tracked in #3289)** Add locking around changes to a workspace host. For example, the cron job that will terminate a host checks that it is `state=draining` and has `load_count=0`. But it would be possible for that host to switch to `ready` and accept a job (incrementing `load_count`) from another PL server, before we manage to switch it to `state=terminating`. To fix this, we should lock the `workspace_hosts` row that we are about to terminate, and each host should check its `status` and increment its `load_count` before it reports that it accepted the job.

* [x] @tdy Add a cron job to look for workspaces that are nearing the 12-hour timeout and change their `message` to say `WARNING: this workspace will stop in XX minutes. Click "Reboot" to keep working.`

**Comment by tdy** [comment]
@mwest1066 can you clarify these items when you get a chance:

* [ ] `cron/workspacesLoad.js` uses "Running" in some places where it should be "Running"
    * **Not sure what this typo should be fixed to**
* [ ] Add file logging to `/var/log/prairielearn.log` on workspace hosts and add it to the files that amazon-cloudwatch-agent sends to cloudwatch.
    * **Is this supposed to be `server.log` (`config.logFilename`)?**
* [ ] Use the `Name` tag to group workspace hosts and filter the instances. (so `"Name": "workspace-prod"` or something like that).
    * **Where is this?**

**Comment by tdy** [comment]
@mwest1066 bump ^

**Comment by mwest1066** [comment]
> * [ ]  `cron/workspacesLoad.js` uses "Running" in some places where it should be "Running"

Sorry! It uses "Running" in some places where it should be "Ready".

I'm not sure this is still true?

> * [ ]  Add file logging to `/var/log/prairielearn.log` on workspace hosts and add it to the files that amazon-cloudwatch-agent sends to cloudwatch.
>   
>   * **Is this supposed to be `server.log` (`config.logFilename`)?**

I actually think we shouldn't worry about this. However, it would be good to add more `logger.info()` calls when we launch a workspace, kill a container, etc.

> * [ ]  Use the `Name` tag to group workspace hosts and filter the instances. (so `"Name": "workspace-prod"` or something like that).
>   
>   * **Where is this?**

This is for the production deployment setup. Maybe we can break that out into a separate issue?

**Comment by mwest1066** [comment]
> > * [ ]   `cron/workspacesLoad.js` uses "Running" in some places where it should be "Running"
> 
> Sorry! It uses "Running" in some places where it should be "Ready".

I think we were confused about Running/Ready with workspaces versus workspace_hosts. I think workspaces should be "Running", while workspace_hosts should be "Ready"?

**Comment by tdy** [comment]
Closing -- unresolved items have been ported to #3179, #3266, #3288, #3289
