### ISSUE TITLE
Chunks deployment plan

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3122]
* [x] Make a new manually-created PL server called `chunk1` with `chunksConsumer=true`, running the shib config for `www.prairielearn.org`.
* [x] Make a target group (or autoscaling group) called `chunkGroup` containing just `chunk1`
* [x] Make a load balancer at `www.prairielearn.org` with rules:
```
/pl/login -> chunkGroup
/pl/shibcallback -> chunkGroup
/pl/course_instance/DEV101_ID/instructor/* -> prairielearn.engr
/pl/course_instance/DEV101_ID/* -> chunkGroup
* -> prairielearn.engr
```
* [x] Merge the chunks PR #2891 
* [x] Deploy the new `master` to `prairielearn.engr` with `chunksGenerator=true` and `chunksConsumer=false`
* [x] On `prairielearn.engr`, do a sync of DEV 101 to trigger generation of all chunks for it
* [x] Check that DEV 101 works in both instructor (served by `prairielearn.engr`) and student (served by `chunk1`) modes
* [x] Make more `chunkN` servers and add them to `chunkGroup`
* [x] Sync another course to trigger chunk generation, and add a load balancer rule to redirect it to `chunkGroup` as well
* [x] Set up Google and AzureAD auth on `www.prairielearn.org`
* [ ] News item
* [x] Generate chunks for all courses (needs new code)
* [x] Resolve #3136 
* [x] Merge and deploy #3091 
* [ ] Fix all "High Impact" bugs listed at https://github.com/PrairieLearn/PrairieLearn/projects/12
* [x] Redirect `/socket.io` to student-route and check that workspaces and external grading work.
* [ ] Check whether LTI works with www.prairielearn.org
* [x] What about ZJUI courses using hardcoded IP address for PL to control exam access? Add apache rewrite rule to exempt the ZJUI course instances from redirection to prairielearn.org.
* [x] Add a redirect rule in Apache on `prairielearn.engr` to redirect `prairielearn.engr -> www.prairielearn.org`
* [x] Change load balancers to balance all student routes, not just specific course instances
* [x] Add code to PL so chunk servers can pull config automatically (re-use workspace host code):
    * [x] Get real `instanceId`
    * [x] Get config from SecretsManager
* [x] Change chunk servers to move `/tmp/pl-chunked-courses -> /pl-chunked-courses` to survive reboot
* [x] Set up AMI-building scripts for chunk servers
* [ ] Deploy chunk servers into autoscaling group
* [ ] Set up autoscaling

Issues:
* [x] Use chunks code in test suite
* [x] What's the local dev story?
* [x] The "attached files" functionality. This needs local disk at the moment until #3035 is merged. Maybe we can disable this temporarily?
* [x] Websockets -- problem was solved by using sticky sessions
* [ ] Can we limit the number of DB connections? Postgres prefers fewer DB connections.

**Comment by nwalters512** [comment]
Chunk servers have long since been running in production 🎉
