### ISSUE TITLE
Issues with issues

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4093]
There are lots of problems with the way issues work on PL. This is a list of some problems that I've experienced, or discussed with @cheeren , or seen on GitHub.

* [ ] Issues right now are one-way communications. There is no way for students to see the issues they have raised, as well as a status (#1438).
* [ ] There needs to be a way for instructors to add a comment/reply that students can see about the issue resolution, as well as internal comments visible only to instructors (#1502).
* [ ] Filter by assessment.
* [ ] Consider cross-course instance issues: instructors should not have access to issues that are from a different course instance, unless they have course permission beyond the instance (#1574).
* [ ] Potential bug: report issue as another user (see #1505).
* [ ] Email instructors when an issue is raised.
* [ ] Email students when their issue is resolved or commented on (also see customizable email templates, #3029).
* [ ] Better way to close multiple issues at a time (#3341, #2154).

**Comment by jonatanschroeder** [comment]
Emailing instructors and students via PL should probably require #2075 to be handled, as well as some kind of settings where users would need to specify if and how they want to receive a notification.

**Comment by andrewstec** [comment]
Based on Cinda and Anthony's prior discussion, there is a possibility to work on some of these issues and create a minimal feature. The feature could notify an instructor each time an issue is raised. If we add an email field to each user, the email reply could be set to the email of the person who reported the issue (ie. the student user). AWS Canada now offers SES (Simple Email Service), which makes it safer to send email to Canadian users without impacting privacy.

There is also the possibility to build out the full feature, with having support for a comment area where the issue can be tracked, in which case we would want Matt's approval due to the amount of code, and we would want to setup a project board to manage this feature. 

**Rough outline of first steps:** 

Spike: Determine if Amazon SES is integrated with Prairie Learn application. AWS.SES and SES Class sendEmail() method not found in quick trace, so ask at meeting.

Story: As a faculty member, I would like to receive an email notification each time an issue is opened by any student user role and be able to reply to the student.

Requirements: Student email address is added to the users table.

@cheeren @winstan

**Comment by cycomachead** [comment]
Commenting to follow along - it would really help a lot to and some at least reply functionality in PL. :)
