### ISSUE TITLE
pl-symbolic-input: support for implicit multiplication "2x" instead of "2*x"

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#5879]
Maths users often type expressions "2x" or "cos(3x)" and are surprised by the invalid message.  This is well-known to PL people and I have a "Homework 0" specifically to educate about this.  But its hard for users not to see it as a limitation---its probably the most common complaint I get in my course.

### related issues

Note: perhaps this is dupe but I couldn't find a particular issue that refers to it.  I will try to collect related issue and linked them here:
  - #4376
  - #3469

### non-starters

SymPy has a `parse_expr` with various `transformation` support that will do this.  But it uses `eval`.  See upstream https://github.com/sympy/sympy/pull/12524 and https://github.com/sympy/sympy/issues/10805.

**Comment by cbm755** [comment]
I did a bit of digging and I notice that SymPy's `parse_expr` (which I mentioned is a non-starter) calls another function `stringify_expr` which only calls standard lib `tokenize` and can apply SymPy's transformation functions (including `implicit_multiplication_application`). 

Here's a proof of concept:
```python
import sympy
from sympy.parsing.sympy_parser import stringify_expr
from sympy.parsing.sympy_parser import standard_transformations
from sympy.parsing.sympy_parser import implicit_multiplication_application
# todo: may want `function_exponentiation` as well

T = standard_transformations + (implicit_multiplication_application, )

s = "14x cos 2x"
out = stringify_expr(s, {}, {}, T)
print(out)

# not quite right with empty local_dict and global_dict
s2 = "10sin**2 x**2 + 3xyz + tan theta"
out = stringify_expr(s2, {}, {}, T)
print(out)
```
The latter example will give "s*i*n" I think b/c the local_dict and global_dict are empty.

### TODO

- [x] basic PoC 
- [x] check that `stringify_expr` does not call `eval`.
- [x] check that the `standard_transformations` and `implicit_multplication_application` do not call `eval`
    - [ ] **carefully** check that the `standard_transformations` and `implicit_multplication_application` do not call `eval`
- [ ] use appropriate local/global dicts in PoC.
- [ ] check if `python_helper_sympy.py` already uses the local/global dict idea.
- [ ] integrate into `python_helper_sympy.py`

**Comment by cbm755** [comment]
Additional background: if you one does not care about security, you can easily use `parse_expr` in SymPy:
```python
>>> import sympy
>>> from sympy import parse_expr
>>> from sympy.parsing.sympy_parser import standard_transformations
>>> from sympy.parsing.sympy_parser import implicit_multiplication_application

>>> T = standard_transformations + (implicit_multiplication_application,)
>>> parse_expr("2x", transformations=transformations)
2*x
```
I'm sure, but have not tried, that one can hack this into the `def parse():` of one's `server.py`.  The downside mentioned above is that `eval` will be called which means users can execute arbitrary code on your server.

My attempt above is to get the benefits of `implicit_multiplcation_application` transform without calling `parse_expr`.

**Comment by cbm755** [comment]
Proof of concept with sympy's default `global_dict`:

```python
from sympy.parsing.sympy_parser import stringify_expr
from sympy.parsing.sympy_parser import standard_transformations
from sympy.parsing.sympy_parser import implicit_multiplication_application
# todo: may want `function_exponentiation` as well

# straight-up copy-paste job from sympy/parsing/sympy_parser.py to build
# the global_dict
import types
import builtins
from sympy.functions.elementary.miscellaneous import Max, Min

global_dict = {}
exec('from sympy import *', global_dict)

builtins_dict = vars(builtins)
for name, obj in builtins_dict.items():
    if isinstance(obj, types.BuiltinFunctionType):
        global_dict[name] = obj
global_dict['max'] = Max
global_dict['min'] = Min


T = standard_transformations + (implicit_multiplication_application, )

s = "14x cos 2x"
out = stringify_expr(s, {}, global_dict, T)
print(out)

s2 = "10sin**3 x**2 + 3xyz + tan theta"
out = stringify_expr(s2, {}, global_dict, T)
print(out)
```
The two outputs here are:
```
Integer (14 )*Symbol ('x' )*cos (Integer (2 )*Symbol ('x' ))
```
and
```
Integer (10 )*sin (Symbol ('x' )**Integer (2 ))**Integer (3 )+Integer (3 )*Symbol ('x' )*Symbol ('y' )*Symbol ('z' )+tan (Symbol ('theta' ))
```
