### ISSUE TITLE
exampleCourse update

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#602]
#Todo 
- [ ] Make sure at least 1 example of each question type
- [ ] Rename question directories to include what type of question they are
- [ ] Make sure we highlight differences between exams and homeworks
- [ ] Make sure assessment names/configurations show how they're different

**Comment by mwest1066** [comment]
Lots of work has and is going on in this area.
