### ISSUE TITLE
allow-blank in pl-rich-text-editor, and pl-file-upload

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#6350]
As discussed in #6342, opening an issue to track the feature to add `allow-blank` in `pl-rich-text-editor`, and `pl-file-upload`

Use-case" essentially any of the elements that can be used to ask "survey-type" questions where answers don't have to be "valid" should have the option where they can be skipped (different from answered).

While I'm creating this issue, here are other first-party elements that may benefit from `allow-blank` options:

## PRs in progress 

- [x] [pl-multiple-choice](https://prairielearn.readthedocs.io/en/latest/elements/#pl-multiple-choice-element) #6119
- [x] [pl-checkbox](https://prairielearn.readthedocs.io/en/latest/elements/#pl-checkbox-element) #6119 
- [x] [pl-order-blocks](https://prairielearn.readthedocs.io/en/latest/elements/#pl-order-blocks-element) #5496 
- [x] [pl-rich-text-editor](https://prairielearn.readthedocs.io/en/latest/elements/#pl-rich-text-editor-element) #10298 
- [x] [pl-file-upload](https://prairielearn.readthedocs.io/en/latest/elements/#pl-file-editor-element) #10317 
- [x] [pl-dropdown](https://prairielearn.readthedocs.io/en/latest/elements/#pl-dropdown-element) #10298 
- [x] [pl-matching](https://prairielearn.readthedocs.io/en/latest/elements/#pl-matching-element) #10298 

And some that probably wouldn't benefit that much from `allow-blank`, but may be good to add for completeness.

- [X] ~~[pl-string-input](https://prairielearn.readthedocs.io/en/latest/elements/#pl-string-input-element)~~
- [X] ~~[pl-matrix-component](https://prairielearn.readthedocs.io/en/latest/elements/#pl-matrix-component-input-element)~~
- [ ] [pl-threejs](https://prairielearn.readthedocs.io/en/latest/elements/#pl-threejs-element)

**Comment by jonatanschroeder** [comment]
> * [ ]  [pl-string-input](https://prairielearn.readthedocs.io/en/latest/elements/#pl-string-input-element)
> * [ ]  [pl-matrix-component](https://prairielearn.readthedocs.io/en/latest/elements/#pl-matrix-component-input-element)

These two already have the option.

**Comment by firasm** [comment]
Ah okay - then the documentation should be updated because it doesn't show up in the list of params.

**Comment by natmarbal** [comment]
#6119 is an open PR for allowing blank submissions of `pl-checkbox` and `pl-multiple-choice`.

**Comment by firasm** [comment]
Thanks, updated the post above!

**Comment by nritschel** [comment]
Note that pl-file-upload does require a (non-empty) "file-names" attribute that specifies the requested file names for the upload. All other files are skipped. I could technically make file-names optional and allow arbitrary file uploads, but I have a feeling that this is a much more severe change than you were aiming for. 

If you think file uploads should be changed, could you give me a bit more context how exactly you image the handling to work?

**Comment by firasm** [comment]
Ah - good point. 

The intention for this feature is *not* to allow arbitrary file upload, but rather, to allow students to submit the question **if there is no file uploaded** in a part of a question.

That said, there is a [separate issue here](https://github.com/PrairieLearn/PrairieLearn/issues/3063) about allowing files of arbitrary file name.

**Comment by jonatanschroeder** [comment]
An `optional-file-names` argument may be a good solution that takes care of this issue. In that case, providing either one of `file-names` or `optional-file-names` (or both) would be enforced. I'd suggest a separate PR for that for easier review.

**Comment by eliotwrobson** [comment]
The file upload element has a few open issues that handle overlapping semantics, including the issue firas linked and how the files are previewed: https://github.com/PrairieLearn/PrairieLearn/issues/4351

I think the best approach is to comb through the issues list and redefine the semantics to capture as many of the use cases described as possible.

**Comment by jonatanschroeder** [comment]
That is a good point. Just to add: one approach recently implemented is in workspaces, which now [allows graded files to use wildcards](https://prairielearn.readthedocs.io/en/latest/workspaces/#infojson). In that context, graded files using wildcards are considered optional, while graded files without wildcards are considered mandatory. I'm not sure how this could be translated here, but it may be a good starting point, and having consistency with that context is probably a good idea.

**Comment by nritschel** [comment]
> That is a good point. Just to add: one approach recently implemented is in workspaces, which now [allows graded files to use wildcards](https://prairielearn.readthedocs.io/en/latest/workspaces/#infojson). In that context, graded files using wildcards are considered optional, while graded files without wildcards are considered mandatory. I'm not sure how this could be translated here, but it may be a good starting point, and having consistency with that context is probably a good idea.

After thinking/looking a bit more into this, unix-style wildcards for file names seem like a good separate idea to me (and not too hard implementation-wise), but they don't quite solve the optional file issue. I think the most obvious use case for this is to allow a specific optional file (e.g., @firasm's initial use case of a survey, or to give students the option to add a README.txt or some other kind of explanation/documentation to submissions), and that isn't really encodable through wildcards.

Maybe the most reasonable option, also to ensure backwards compatibility in case someone used wildcard characters like `?` or `*` in `file-names` to refer to actual file names, is to add a new parameter `optional-file-names` with the semantics as you suggested above, and have only that parameter allow wildcards to essentially whitelist both specific file names or name ranges.

**Comment by jonatanschroeder** [comment]
> that isn't really encodable through wildcards.

Technically you can use `README[.]txt`...

**Comment by jonatanschroeder** [comment]
> Maybe the most reasonable option, also to ensure backwards compatibility in case someone used wildcard characters like `?` or `*` in `file-names` to refer to actual file names, is to add a new parameter `optional-file-names` with the semantics as you suggested above, and have only that parameter allow wildcards to essentially whitelist both specific file names or name ranges.

I would be ok with such an approach.

**Comment by nritschel** [comment]
So I've worked on the pl-file-upload and besides some minor clean-ups in the code I have a [fully functional version](https://github.com/nritschel/PrairieLearn/tree/file-upload-wildcards). Posting some screenshots here in case there's feedback on the design.

I've tried hard to keep everything backwards compatible, so if you don't use `optional-file-names`, then nothing should change/break. If there are `optional-file-names` (potentially in addition to mandatory `file-names`), I always render the required names first. `optional-file-names` are effectively separated into those with wildcards and those without. Non-wildcard names are listed first, then come all the allowed patterns for wildcards:

<img width="795" alt="Screenshot 2024-07-31 at 3 02 04 PM" src="https://github.com/user-attachments/assets/2afcbd26-8dab-4642-ac06-f0b7bf18b62e">

When files are uploaded, non-wildcard optional files get "filled" just like mandatory files as there's always a 1:1 match between an accepted and a potentially uploaded file. For wildcards, to show that there might be any number of files added, the list entry doesn't fill, but simply prepends the uploaded file and then lists the wildcard again to signal that there's more that could be uploaded:

<img width="817" alt="Screenshot 2024-07-31 at 3 03 41 PM" src="https://github.com/user-attachments/assets/776476d6-a8d5-4412-9025-c328832e80c7">

Implementation-wise, the main thing of note is that I convert wildcards into regular expressions on the server and then use the result both there and in the JS code that handles the client-side file processing. I've looked into some libraries for glob matching, including the approach that is currently used in workspaces, but the problem is interoperability with the JS code and the general bloat that codes with handling more complex cases like `**/*` that are not relevant for processing single files.

A few more design notes/potential TODOs:

* Students should probably have the option to delete optional files on the client-side, as currently they can only be replaced.
* It might become necessary to define a fixed maximum number of files that can be uploaded. For workspaces this seems to be a global setting, but here it might be more reasonable to add another parameter to the `pl-file-upload` element.
* Generally, the feedback for `pl-file-upload` isn't great right now. Besides my other changes, I've added a box similar to other elements that at least shows format error messages at all in the question panel, but the submission panel is currently completely blank and should at the very least also show errors that indicate why a submission was marked as invalid, and ideally a list of the uploaded files. 
*

**Comment by jonatanschroeder** [comment]
Can you submit a PR so that we can take a look at the code in practice? I like the general approach you have taken.

**Comment by firasm** [comment]
Thanks for the screenshots and description @nicknytko! I found them very helpful to read as it would've taken me a while to get things up and running to play with this. 

Overall I'm also in favour of this approach, but the one annoying for me is that `file-names` is a required parameter. If a question had the requirement to upload "any" .py file, one would still need to list the "ideal" filename, and then another box for any files matching.... do I have that right ?

It would be nice if `file-names` could also take on a value of "None" (and then nothing would get displayed for it) and only the optional file would appear in the list of things they have to upload.

--------

The other things to check is what happens if there is only an optional file uploaded and when there are no files uploaded, but that I can try on your PR myself - which I'm now glad there is 😂!

**Comment by firasm** [comment]
Even though `pl-file-upload` is not quite "done", it's being significantly enhanced in #10317 which would add the functionality of `allow-blank` but without a parameter called `allow-blank`. 

For that reason, I'm going to close the issue.
