### ISSUE TITLE
Allow undo of some Question Sharing Operations

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#7895]
There are multiple operations involved in sharing questions with another course: 
- Picking the course sharing name
- creating sharing set
- sharing a sharing set to a course
- adding a question to a sharing set

The MVP (https://github.com/PrairieLearn/PrairieLearn/pull/6770) makes all of these operations final, none of them can be un-done. 

There is a good reason for some sharing operations to be permanent--once someone has imported a question into one of their assessments in their JSON file, we cannot allow you to un-share it with them, because it would break their assessment. However, there are lots of operations that we can allow to be undone. 

-  [x] picking the course sharing name: Can be changed as long as no one has imported a question from your course yet (#9860)
- [ ] creating sharing set
     - [ ] deletion: can be deleted _unless_ a course has been given permission to the sharing set (#10050)
     - [ ] renaming: we can allow users to rename sharing sets at any time, as the name of the sharing set is only ever visible to the creator (#10065)
- [ ] sharing a sharing set with a course: can be undone as long as that course isn't importing any questions from that sharing set
- [ ] adding a question to a sharing set: can be undone as long as no one is importing that question with permissions granted by that sharing set
    - [ ] (check if the question is being used in assessment_questions by a course other than its home course. This will require joining assessment_questions to asessments (or something like that) to get the course_id. 
 - [ ] publicly sharing the source code of a question (#10031)

examples of how to do the JSON editing stuff are here: https://github.com/PrairieLearn/PrairieLearn/commit/408576972c0d205fa88efec491447012e97bfafc

This could be split into separate PRs for each of these operations, or some of them could be combined. Adding these should greatly enhance the usability of the sharing UI/UX.

**Comment by SethPoulsen** [comment]
Once 'public sharing' is implemented, a question that is publicly shared can be un-publicly shared if no other course have used it yet.

**Comment by jeffgerickson** [comment]
_Revising_ shared questions has to be supported.  (The question might have bugs; the question might rely on external libraries whgose behavior changes; the question might make assumptions about external resources that are no longer true; etc etc.)

But then questions can still be effectively unshared by revising them into something trivial.

**Comment by SethPoulsen** [comment]
Hi Jeff, you are right on all points. 

Revising the questions must be supported and in fact it _is_ supported. Any edits made to a shared question are propagated to all courses using that questions, PrairieLearn is only keeping a single copy of the question that all the courses are looking at. 

 > questions can still be effectively unshared by revising them into something trivial
That is correct at the moment. So for now you must have some sort of trust that whomever you are consuming questions from won't do that. In the future we are hoping to have some sort of versioning system where PrairieLearn will maintain prior versions of a question, that will solve this problem

However, all of this is rather tangential to the point of _this_ particular issue, which is about operations on sharing information, not about editing question content itself.
