### ISSUE TITLE
PL v3 roadmap to release

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#817]
# Roadmap
- Development
- Examples
- Documentation
- Announcement

# Development

## Code auto-graders
- [x] Change the way docker containers are run to make them faster (switch from AWS Batch to a custom docker-runner)
- [x] Change the way we pass information to docker (currently, we use networking to pull things in from S3, which forces the docker to have network enabled, which we don't want, so we're going to add stuff to the docker image from the custom docker runner, code pushing/pulling will be done by this custom docker runner)
- [x] Change the directory structure inside the docker container (finalize the conventions for names inside the docker container - pieces of code that are pulled into this container get put in a bunch of confusing places)
- [x] For a small number of standard languages (e.g., python) provide a PrairieLearn auto-grader that improves on what's used in the example Fibonacci questions (#940)
- [x] Modify Fibonacci example questions to use the PrairieLearn auto-grader (#940)
- [x] Create tools so both instructors and admins can see things like: job times, queue length, etc.
- [x] Parameterize `test/` files before copying to the container somehow? Jake has questions with many test cases, but each variant only wants a small subset of them.
- [x] Re-submitting for a variant should cancel the outstanding jobs, which should websocket back to show that they were canceled.
- [x] Shut off networking on the grading Docker containers.
- [x] Report an issue whenever an autograder has an error.
- [x] Run multiple jobs on each grader instance.
- [x] Report "job start" back to PrairieLearn so we can estimate the number of pending jobs.
- [x] Add per-question Docker config
  - [x] Time limits
  - [x] Memory limits

## Javascript support
- Question code
    - [x] Enable the use of `server.js` as an alternative to `server.py` (error if both are present)
    - [x] Enable header dependencies, same as elements (e.g., see `info.json` in `pl_file_editor`)
    - [x] Create at least one example question with client-side code (e.g., a drawing question)
- Element code
    - [x] Enable the use of `<pl_elementname.js>` as an alternative to `<pl_elementname.py>` (error if both are present)

## Error handling and debugging
- [x] Implement error handling with websockets
- [x] Distinguish stdout - e.g., calls to `print()` - from errors and implement display with websockets
- [x] Create linter that does not allow code with `print()` calls (for example) to be pushed to production
- [x] Add a debug button (visible to instructors) that toggles display of lots of information about exactly what is happening (including, at minimum, the contents of `data` as it changes)
- Log more things to the errors table:
    - [x] If you try to load a file in a question and the file is missing or empty
- [x] `test()` should take a parameter (correct, incorrect, invalid)
- [x] Redesign test button logic and UI
- [x] Create tool to run `server.py` (or `server.js`) from the command line

## Grading
- [x] Make credit work per-question rather than per-assessment.
- [x] Have an option in `infoAssessment.json` to give or not give partial credit
- [x] Get rid of `<pl_variable_score>` (elements should indicate whether or not they are correct)
- [x] Consider the use of "question groups" (i.e., separate questions with a common set of parameters) instead of or in addition to the use of partial credit in single questions
- [x] Allow `grade()` in `server.py` to modify the number of tries left (and maybe other things)
- Consider making these changes:
    - [x] Reintroduce "1 try left" on Grading button for questions with multiple `triesPerVariant`
    - [x] Don't increase `value` for questions with multiple `triesPerVariant` unless 100% on first try for a new variant (the reason this is non-trivial is that it requires keeping track of try number, which we don't currently do)
    - [x] Make `History` show scores and not points
    - [x] Stop adding to `History` when points are already at max (avoid long history lists) and make the last entry equal to the amount of points that were actually added (i.e., the difference between `max_points` and all prior entries in `points_list`)
    - [x] Remove the option to let `value` change (i.e., always keep it constant)
    - [x] Bring back the grey boxes in `History`
- Add tools for instructors:
    - [x] Allow an instructor to add an arbitrary number of points to all students for a given question
    - [x] Allow an instructor to "reset" a given question

## Elements
- Improve numeric and symbolic input elements (`<pl_matrix_input>`, `<pl_number_input>`, and `<pl_symbolic_input>`)
    - [x] Support numpy format for matrices
    - [x] Support the use of commas to separate entries in MATLAB format for matrices
    - [x] Consider redesign (e.g., consolidate matrix and number input, or numeric and symbolic input)
    - [x] Support for symbolic matrices
    - [x] Better support for units
    - [x] Add client-side validation
    - [x] Decide if changes are needed to methods of comparison
    - [x] Show students the interval within which a submitted answer must be in order for this answer to be considered correct (based on method of comparison)
- [x] Add element for string input
- [x] Throw error when a function tries to modify something that cannot be modified
- [x] Decide if an error should be thrown when a submitted or correct answer does not exist, but should (e.g., see `render()` or `grade()` in `<pl_number_input>` - may want to add a required attribute that says if `correct_answer` will or will not be specified)
- [x] Support API for answer submission outside of the browser (e.g., in a terminal)
- [x] Auto-save in `<pl_file_editor>` (even just with local storage?) and maybe in all elements
- [x] Rename `info.json` to `infoElement.json`
- [x] Is it possible to have some sort of random-file element. A common use-case is giving students one of several code files or figures. We want to block access to the other ones, even if they have guessable filenames (like `fig1.png`, `fig2.png`, etc).
- [x] Should we make it so that element (and server) functions just modify data rather than needing to return it. The return seems completely redundant.

## Questions
- [x] Rename `info.json` to `infoQuestion.json` (with appropriate backward-compatibility)
- [x] Reconsider parts of `data` are passed to what functions in `server.py` (e.g., give `file()` access to `data['submitted_answers']` when it exists)
- [x] Error when a server function tries to modify a part of `data` that can't be modified
- Rewrite HTML parsing
    - [x] Make it much stricter (e.g., require proper close of each PL element)
    - [x] Create linter so existing questions that don't pass strict parsing are caught
    - [x] Clarify rules for order in which things get evaluated
    - [x] Error when finding an element name `<pl_*>` whose name is not known
    - [x] Support the use of only one question, submission, and answer panel (e.g., support the use of duplicate names in different panels)
    - [x] Collapse all submission panels except the most recent, and add expander buttons.
- [x] Consider replacing the `infoQuestion.json` attribute `singleVariant` with an `infoAssessment.json` attribute `generation` that is specified per-question and has value `static` or `dynamic` (default=`dynamic`)

## Bug fixes
- [x] Instructor pages should not generate a new variant on page reload
- [x] Weights should be floats and not integers for questions with multiple input elements
- [x] Add time-out to python caller (there are time-outs for individual function calls but not for the whole thing)
- [x] Do not run course code as root
- [x] Seed random number generators (e.g., with vid)

## System-wide improvements
- [x] Verify consistent naming
- [x] Delete `question-servers` and `freeformPythonLib` (migrate contents elsewhere)
- [x] Speed up "Load from Disk"
- [x] Improve UI
- [x] Track and display statistics on variants (e.g., A/B testing to say whether or not certain variants are significantly harder than other variants) to instructors
- jsonify support for:
    - [x] numpy arrays (so instructors need not use `.tolist()` and `numpy.array()`)
    - [x] complex numbers
- [x] Add "create new retry" (or "reset") button so that if question generation was broken (e.g., for a timeout problem) we can quickly fix it in an exam situation
- [x] Abort creation of exam instance on error in `generate` (question) or `prepare` (any element), forcing students to try again.
- [x] Every time we call question code we should store how long it takes in the db.
- [x] For problems with manual grading, consider redesign of UI because students are done when they `Save` (no need to hit `Grade`).
- [x] Consider making the "next question" button also save.

## JSON serialization (new plan)
- [x] Create library functions `to_json()` and `from_json()`
- [x] Add support in elements for `correct_answers` that are encoded using `to_json()`

## JSON serialization (old plan)
- [x] sympy_matrix should be encoded as a 2-list of strings
- [x] a white-list should be used to say what parts of I/O to encode and decode
- [x] symbolic expressions should be encoded and decoded with AST, with a white-list for expressions and for variables
- [x] you should auto-compute the list of “free variables” from a symbolic expression for encode (this is easy, there is a function that does this) and include them as a separate key-value pair
- [x] the white-list of expressions should be hard-coded and we should be open to expanding this list based on feedback (feature requests) but should not put it in the hands of instructors to decide
- [x] parsing raw submissions may be different from encode and decode, even if they use the same underlying code for most parts of the process
- [x] should refactor code to pull the AST-eval thing into a library
- [x] Remember to prefix keys by “_” to indicate that they are reserved

**Comment by mwest1066** [comment]
Long since released!

**Comment by nwalters512** [comment]
Is there anything here we want to try to break out into smaller issues? v3 on a whole is shipped but some things enumerated here may be worth looking at again.

**Comment by mwest1066** [comment]
I agree that there is lots of good things here that we might want to think about again. I’ll re-open this.

**Comment by mwest1066** [comment]
I split out all the remaining useful bits of this into separate issues. Closing.
