### ISSUE TITLE
List of sprocs that can be converted to libs

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#8893]
This is an (actively maintained) list of all the sprocs that should be converted to functions/queries/libraries in the near future.

### Only called from JS/TS code, not from SQL code:

* Sync process:
  * [ ] sync_assessments.sql
  * [ ] sync_course_instances.sql
  * [ ] sync_news_items.sql
  * [ ] sync_questions.sql
  * [ ] sync_question_tags.sql
* System admin (cron, stats, etc.):
  * [ ] grader_loads_current.sql
  * [ ] server_loads_current.sql
  * [ ] server_usage_current.sql
  * [ ] workspace_loads_current.sql
  * [ ] grading_jobs_stats_day.sql
* Admin:
  * [ ] courses_update_column.sql
* Regular production functionality:
  * [ ] users_select_or_insert_and_enroll_lti.sql (legacy, may be removed without converting)
  * [ ]  assessment_instances_grade (#13152)
  * [ ]  instance_questions_grade
  * [ ]  variants_update_after_grading (#13142)

### Called from SQL code, but not from other sprocs

* [ ] authz_assessment_instance
* [ ] authz_course
* [ ] authz_course_instance
* [ ] ip_to_mode
* [ ] interval_hist_thresholds
* [ ] assessments_format_for_question
* [ ] instance_questions_next_allowed_grade
* [ ]  format_interval
* [ ] groups_uid_list
* [ ] question_order
* [ ] admin_assessment_question_number
* [ ] group_info
* [ ] assessment_instance_label
* [ ] format_date_iso8601
* [ ]  users_is_instructor_in_course
* [ ]  users_select_or_insert

### Custom aggregate functions

* [ ] array_avg
* [ ] array_var
* [ ] histogram
* [ ] array_histogram

### Referenced from other sprocs (may need to wait for other sprocs to be converted):

* [ ]  array_and_number
* [ ]  array_increments_above_max
* [ ]  assessment_instances_points (#13152)
* [ ]  authz_assessment
* [ ]  check_assessment_access
* [ ]  check_assessment_access_rule
* [ ]  check_course_instance_access
* [ ]  check_course_instance_access_rule
* [ ]  format_date_full
* [ ]  format_date_full_compact
* [ ]  format_date_short
* [ ]  input_date
* [ ]  instance_questions_calculate_stats
* [ ]  instance_questions_points
* [ ]  instance_questions_points_exam
* [ ]  instance_questions_points_homework
* [ ]  issues_insert_for_variant
* [ ]  jsonb_array_to_double_precision_array
* [ ]  jsonb_array_to_text_array
* [ ]  random_unique
* [ ]  scores_to_points_array
* [ ]  users_are_instructors_in_any_course
* [ ]  users_get_displayed_role
* [ ]  users_is_instructor_in_course_instance
