### ISSUE TITLE
Question Sharing: Path out of Beta

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#9397]
I had a meeting with @nwalters512 and @mwest1066, and we discussed 3 needed features to get 

1. A link on the Instructor Sharing Settings page to the course's public sharing page
2. In the sidebar of a question preview, the QID that the question is shared as (which is @course-sharing-name/qid)
3. A way for people to copy the code of shared questions (if the authors desire it).

The first 2 are easy, number 3 has quite a bit of stuff to unpack, so I'll lay out a bit more of the details that we discussed: 

on the Questions Settings page:
- When someone goes to 'publicly share' a question , they should have a checkbox where they can state if they want it to be source available under some CC license (probably only one choice, allowing more choices will be too much trouble. we discussed using CC-BY)
- After publicly sharing, they can hit a button that says 'edit public sharing' or similar so they can either un-share their source by unchecking the box, or check the box to share the source if they hadn't initially (we can't allow people to un-share questions at risk of breaking existing assessments, but we can allow people to un-share source without any negative repercussions)
- add another badge on the page saying if the source is shared

In the JSON: 
- add an 'authors' field to the info.json for questions. This is just a list of emails. We will destructure this into the database so that in the future we can do joins on the email in order to give people usage statistics for their questions based on their email. In the future we may allow adding syntax for people to put their name with their email (e.g. "First Last <name@provider.com>")

In the DB: 
- a new field on questions, 'publicly_shared_source'
- the new 'question_authors' table to mirror the JSON change described above

--------------------------------------

Edit: Adding a TODO list here of all the items mentioned in this thread so we can track completion: 
- [x] A link on the Instructor Sharing Settings page to the course's public sharing page (#9478)
- [x]  In the sidebar of a question preview, the QID that the question is shared as (which is @course-sharing-name/qid) (#9763)
- [ ] authors field in JSON and database (#9790)
- [x] copy button on public shared question previews (#9800)
- [x] sharing course should get a sync error if they try to delete or change the QID of a question that they have shared (#9797)
- [x] limit expensive features (at least workspaces) from publicly-viewable questions (#9902)
- [x] Make sure custom course elements that have client assets (JS, CSS, etc.) work properly
  - [x] publicly shared question previews (#9807)
  - [x] shared questions being used within a course (#9786)
- [x] Fix 'undefined' in taskbar on public question previews (#9094)
- [ ] Move declaration of sharing info for questions into JSON (sharedPublicly, sharingSets, sharedPubliclyWithSource) (#10029)
- [ ] More clear warnings about permissions being granted (for client element files and potentially clientFilesCourse) (#10730)
  - [ ] In the question sharing documentation page
  - [ ] In the  "Add Course to Sharing Set" popover (make it a dialog) on the sharing page
  - [ ] In the "Share publicly" dialog on the question settings page

**Comment by firasm** [comment]
I agree with `CC-BY-NC` - though the license is not really a big deterrent for thieves, the `NC` is important as it allows instructors to request things be taken down because of license restrictions (Chegg, Coursehero, etc...)

**Comment by SethPoulsen** [comment]
Adding a Number 4. based on an error reported on Slack yesterday: 

4. The _sharing_ course should get a sync error if they try to delete or change the QID of a question that they have shared, so that they can't break other people's course syncs

**Comment by mwest1066** [comment]
We'll probably also want to restrict access to expensive features (at least workspaces) from publicly-viewable questions, to avoid giving everyone on the internet a free VM to run their crypto mining.

**Comment by SethPoulsen** [comment]
The main purpose of this issue was to track the huge amount of question sharing work that was done over the summer. 

In a recent conversation with @nwalters512 and @mwest1066 we decided the main important task to finish was allowing some undo operations, which has an issue here: https://github.com/PrairieLearn/PrairieLearn/issues/7895

Also important to follow up with soon is UI editing, which has an issue here: https://github.com/PrairieLearn/PrairieLearn/issues/10891

Since the last few important items are all being tracked elsewhere and this mega-issue is getting very cluttered with things that are already done, I'm going to go ahead and close this issue.
